version: '3.3'
services:
  #backend:
  #  build: ../proto/app.py
  #  ports:
  #    - 9000:9000
  proxy:
    image: envoyproxy/envoy-alpine:v1.14.1
    environment:
      NODE_ENV: development
      loglevel: debug
    ports:
      - 8080:8080
      - 9901:9901
    networks:
      - envoymesh
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
networks:
  envoymesh: {}